### PR TITLE
Rename wt88047 to wt88047.rst

### PR DESCRIPTION
**Pull request by abhishek9650**

### CODE REVIEW

**Comment by vanyasem** [comment]
Please, continue making changes to the old PR #57. There's no need to make a new one.

**Comment by abhishek9650** [comment]
it is for updating the extension why would it not need a new pr

**Comment by vanyasem** [comment]
Because it's related to your old PR. CI will need to pick up the changes and rebuild the docs. Everything should happen in **one** single PR. Thank you

**Comment by abhishek9650** [comment]
where is that rule written ?

**Pull request closed without merging**
