### PR TITLE
HADK, no sudo, hybris-recovery

### PR DESCRIPTION
**Pull request by doniks**

### CODE REVIEW

**Comment by doniks** [comment]
<walks away to learn about squashing commits>

**Comment by z3ntu** [comment]
We can "Squash and merge" directly in GitHub.

**Comment by bhush9** [comment]
That removes authorship information sadly

**Comment by doniks** [comment]
ugh, I think I made it worse ... I tried to squash the commits (never did that before), but it seems I kinda duplicated them all ... 

If you guys want, I can just throw away the fork, do the changes again (no rocket science there) in a new fork

**Comment by bhush9** [comment]
I've manually squashed those changes and commited it.. Thanks for improvements.

**Pull request closed without merging**
