### PR TITLE
Import our document from Google Docs

### PR DESCRIPTION
**Pull request by JBBgameich**
Note: all comments have been removed while converting and cleaning up. If there was something important left, please commit on github again.

I would like to know how clean you want the document to be on the official repository. There are still things to review in the document, maybe it would be better to review and approve them before merging this.

Closes https://github.com/Halium/docs/issues/1

### CODE REVIEW

**Comment by bhush9** [comment]
I think there are some important comments which will need to be transferred in the document.. I've at least split up the development outline here.

**Comment by JBBgameich** [comment]
Is anything missing for merging except the comments?

**Comment by bhush9** [comment]
In general whole planning document needs to be cleared out before we can merge this I believe.. I am working on it still.

**Comment by bhush9** [comment]
As mentioned on telegram.. lets handle comments separately.

**Pull request merged**
