### PR TITLE
Cleaning the docs up

### PR DESCRIPTION
**Pull request by abhishek-mudgal-au13**

### CODE REVIEW

**Comment by abhishek9650** [comment]
@doniks The first change is about removing the old method of installation of rootfs replacing it with jbb's script.
Flex errors: it doesnt matter you fix them this way or that way, i prefer it this way.

**Comment by JBBgameich** [comment]
For the flex issue, sometimes the LANG=C env var fixes it and additionally I think you can set USE_HOST_FLEX=true instead of copying the binary.

**Comment by doniks** [comment]
> For the flex issue, sometimes the LANG=C env var fixes it and additionally I think you can set USE_HOST_FLEX=true instead of copying the binary.

Ah, thanks for clarifying @JBBgameich 

> @doniks The first change is about removing the old method of installation of rootfs replacing it with jbb's script.

I know WHAT you changed, I've seen the diff. I do not know WHY you changed it. Was there a recent discussion about it? I'd expect the commit message to quote and ideally link the consensus. 

> Flex errors: it doesnt matter you fix them this way or that way, i prefer it this way.

Well, if it doesn't matter, why do you have a preference. It so happens that I prefer the environment variable way. (I have the feeling the variable might be closer to the actual rootcause and might aid at some point in a proper fix.) Let's just mention all three please.

**Comment by abhishek9650** [comment]
@vanyasem any reason for halium-install part? coz i have been tired of tellling people to use jbb's script rather than can halium-scripts

**Comment by vanyasem** [comment]
yes. don't just make up decisions on yourself. check previous PR https://github.com/Halium/docs/pull/93

**Comment by abhishek9650** [comment]
I am reopening this pull request , because the changes made above are needed.

**Comment by doniks** [comment]
> I am reopening this pull request , because the changes made above are needed.

I agree that *some* changes are needed. But I don't see most of the review comments in here being addressed. @abhishek9650 around the time that you reopend this pr I think I also heard you say you would open a new pr to only change the undisputed parts of the flex problem. Is that still the plan?

**Comment by doniks** [comment]
ok, so let me summarize what (according to my understanding) you are trying to achieve and then I give you my thoughts on that. 

You want to remove the original script and promote only jbb's script.

Well, I floated a very similar idea once upon a time https://github.com/Halium/docs/pull/93 but it never fully worked out. A couple conflicts remained in my mind. Nobody else seemed to have a really strong opinion about it and lastly there wasn't a very urgent need to solve it. 

* JBBs script does everything on host, which means you need to transport a big image over adb which is slow. I don't have any trouble with the original script and it's faster, so that is what I default to. And actually, I even end up copying stuff out of both of these scripts and rolling my own, which just do one thing at a time rather than all-or-nothing. (PS: haven't checked lately - but I remember at some point some people struggled with image sizes with JBBs script, might be fixed by now) 
* For a full solution of "The One True Install Script". I think it would ideally be hosted inside the halium organisation. However, then *I* personally would also look at the code, and *my* personal opinion is that the multi-file structure and the additional code to create a standalone version out of it are just maintenance overhead that I'd prefer not to have. However, I once had a conversation with JBB and he is reusing some of the pieces in a different manner, so for him the multifile structure is better because it serves some other purpose outside of the script itself. If halium were to take the code and merge it all back into a single file I think there might be a very real risk of losing one of the greatest assests JBBs script has: Namely that JBB actively maintains it! 
* Now, my opinion is hardly the only one that matters, but also back with PR 93, it wasn't like a whole lot of people were actively pushing forward 
* Lastly, what is the actual problem? I stopped at that question the last time around and I still reach pretty much that same point. Both scripts are there. They do what they do. People can port. Well, one actual problem I think is that people might now know where to contribute. But yeah, that doesn't make the points above go away. 

I'd be very happy if someone could sort out the points above. Or alternatively, if there is a consensus to do it anyway despite my concerns - fine. But I find it strange to "just do it" as a "clean up".

**Comment by doniks** [comment]
FYI, I've created a flex PR: https://github.com/Halium/docs/pull/123

**Comment by doniks** [comment]
this has stalled. feel free to reopen if you want to proceed

**Pull request closed without merging**
