### PR TITLE
EGL_PLATFORM=hwcomposer

### PR DESCRIPTION
**Pull request by doniks**

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Did you mean to replace the previous line, or have both?

**Comment by doniks** [comment]
I meant to keep both lines. 

1. I know that the line WITH variable is required on some devices (deb being one)
2. I do not know whether the line WITHOUT is ever the correct one, but it was there first ... so I thought I leave it. If we have some clear indication that it never actually works without the variable then we could delete it

**Comment by vanyasem** [comment]
@doniks you should *always* export  `EGL_PLATFORM`

[Quoting](https://t.me/halium/40856) @bhush9: 
> Bhushan Shah, [05.01.18 15:11]
> test_hwcomposer alone will never work
> 
> Bhushan Shah, [05.01.18 15:12]
> always export EGL_PLATFORM

**Comment by doniks** [comment]
thx. updated

**Pull request merged**
