### PR TITLE
Detailing debug network setup

### PR DESCRIPTION
**Pull request by Flohack74**
... and dont forget so squash this, I fell completely out of sync with my original branches ^^

### CODE REVIEW

**Comment by JBBgameich** [comment]
Shouldn't this work using the `ip` commad instead of `ifconfig` too? `ifconfig` is deprecated in debian and ubuntu

**Comment by Flohack74** [comment]
I am built 1974, sorry if I am using old Linux commands :) - And my MAC addy was empty, and I could not bring up the interface without. So its just an optional step maybe.

**Comment by mariogrip** [comment]
Ha! I also still use `ipconfig` :P

**Comment by Flohack74** [comment]
Whats with this now?

**Comment by LNJ2** [comment]
I think we should use up-to-date tools, so please update the commands to use `ip`. :)

**Comment by doniks** [comment]
> I'm also not sure if assigning a mac adress is neccesary, it worked for me even when only assigning it a ip adress.

I think it's needed on some devices, where the interface comes up with all zeros as mac address

**Comment by Flohack74** [comment]
Finally found time to fix this up :)

**Pull request merged**
